#recompile core and compiler_builtins because it is not supported for our host triplet
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-simpleRustKerneltt.json"

#use for running in QEMU:
[target.'cfg(target_os = "none")']
runner = "bootimage runner"